export enum CalendarsActionType {
    SET_CALENDARS = 'SET_CALENDARS',
    ADD_CALENDAR = 'ADD_CALENDAR',
    EDIT_CALENDAR = 'EDIT_CALENDAR',
    DELETE_CALENDAR = 'DELETE_CALENDAR',
    CLEAR_CALENDARS = 'CLEAR_CALENDARS',
}
