export enum ConstraintsActionType {
    SET_CONSTRAINTS = 'SET_CONSTRAINTS',
    ADD_CONSTRAINT = 'ADD_CONSTRAINT',
    EDIT_CONSTRAINT = 'EDIT_CONSTRAINT',
    DELETE_CONSTRAINT = 'DELETE_CONSTRAINT',
    CLEAR_CONSTRAINTS = 'CLEAR_CONSTRAINTS',
}
